name: sewac_citizen_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter

  # =========================
  # UI
  # =========================
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1

  # =========================
  # Maps & Location
  # =========================
  flutter_map: ^7.0.0
  latlong2: ^0.9.1
  geolocator: ^13.0.2
  geocoding: ^3.0.0
  permission_handler: ^11.3.1

  # =========================
  # Image Picker
  # =========================
  image_picker: ^1.1.2

  # =========================
  # Networking
  # =========================
  http: ^1.2.1
  dio: ^5.11.0
  http_parser: ^4.1.2
  mime: ^2.0.0

  # =========================
  # Local Storage
  # =========================
  shared_preferences: ^2.2.3

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/citizen_icon.png

flutter_launcher_icons:
  android: true
  ios: true

  image_path: "assets/citizen_icon.png"

  min_sdk_android: 21

  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/citizen_icon.png"